title: Geha Group

collections:
  postdocs:
    output: true
  grads:
    output: true
  research:
    output: true
  outreach:
    output: true

sass:
  sass_dir: _sass
  style: compressed # or 'expanded' for development